sonar.projectKey=opsagent
sonar.projectName=OpsAgent
sonar.sourceEncoding=UTF-8
sonar.java.source=17
sonar.sources=ops-auth-service/src/main/java,ops-common/ops-common-core/src/main/java,ops-common/ops-common-mq/src/main/java,ops-common/ops-common-mybatis/src/main/java,ops-common/ops-common-observability/src/main/java,ops-common/ops-common-redis/src/main/java,ops-common/ops-common-security/src/main/java,ops-common/ops-common-web/src/main/java,ops-gateway/src/main/java,ops-ticket-service/src/main/java,ops-knowledge-service/src/main/java,ops-rag-service/src/main/java,ops-platform-service/src/main/java,ops-web/src
sonar.tests=ops-common/ops-common-security/src/test/java,ops-ticket-service/src/test/java
sonar.java.binaries=**/target/classes
sonar.java.test.binaries=**/target/test-classes
sonar.exclusions=**/target/**,**/node_modules/**,ops-web/dist/**,**/*.min.js
sonar.coverage.exclusions=**/config/**,**/*Application.java,**/dto/**,**/vo/**,**/entity/**
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S1118
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*Dtos.java
sonar.scm.provider=git
