<script setup lang="ts">
import { ref } from 'vue';
import BaseModal from '@/components/BaseModal.vue';
import InlineError from '@/components/InlineError.vue';
import { itsmApi } from '@/api/modules';
import { observabilityApi, type ServiceNode, type ServiceRelation } from '@/api/observability';
import { relationLabels } from '@/utils/observability';
import { useAuthStore } from '@/stores/auth';
const props = defineProps<{ nodes: ServiceNode[]; edges: ServiceRelation[]; selected?: string }>();
const emit = defineEmits<{ close: []; saved: [] }>();
const auth = useAuthStore(); const busy = ref(false); const error = ref(''); const editing = ref<number>();
const form = ref({ sourceCiCode: props.selected || props.nodes[0]?.ciCode || '', targetCiCode: '', relationType: 'DEPENDS_ON', description: '' });
function edit(edge?: ServiceRelation) { editing.value = edge?.id; form.value = { sourceCiCode: edge?.sourceCiCode || props.selected || props.nodes[0]?.ciCode || '', targetCiCode: edge?.targetCiCode || '', relationType: edge?.relationType || 'DEPENDS_ON', description: edge?.description || '' }; }
async function save() { if (!auth.isAdmin || busy.value) return; busy.value = true; error.value = ''; try { if (editing.value) await observabilityApi.updateRelation(editing.value, form.value); else await itsmApi.createRelation(form.value); edit(); emit('saved'); } catch (cause) { error.value = cause instanceof Error ? cause.message : '关系保存失败'; } finally { busy.value = false; } }
async function remove(edge: ServiceRelation) { if (!auth.isAdmin || !edge.id || busy.value) return; busy.value = true; error.value = ''; try { await itsmApi.deleteRelation(edge.id); if (editing.value === edge.id) edit(); emit('saved'); } catch (cause) { error.value = cause instanceof Error ? cause.message : '关系删除失败'; } finally { busy.value = false; } }
</script>
<template><BaseModal title="管理有向依赖关系" @close="emit('close')"><InlineError v-if="error" :message="error" /><form class="form-grid obs-editor" @submit.prevent="save"><label>来源节点<select v-model="form.sourceCiCode" required><option v-for="node in nodes" :key="node.ciCode" :value="node.ciCode">{{ node.ciName }}</option></select></label><label>目标节点<select v-model="form.targetCiCode" required><option value="" disabled>选择目标</option><option v-for="node in nodes.filter(item => item.ciCode !== form.sourceCiCode)" :key="node.ciCode" :value="node.ciCode">{{ node.ciName }}</option></select></label><label>关系类型<select v-model="form.relationType"><option v-for="(label, key) in relationLabels" :key="key" :value="key">{{ label }} · {{ key }}</option></select></label><label>说明<input v-model.trim="form.description" maxlength="500" /></label><div class="form-actions full"><button v-if="editing" type="button" class="button secondary" @click="edit()">取消编辑</button><button class="button primary" :disabled="busy || !auth.isAdmin">{{ editing ? '更新关系' : '建立关系' }}</button></div></form><section class="obs-relation-list"><h3>已登记关系 · {{ edges.length }}</h3><article v-for="(edge, index) in edges" :key="edge.id || index"><div><strong>{{ edge.sourceCiCode }} → {{ edge.targetCiCode }}</strong><small>{{ relationLabels[edge.relationType] || edge.relationType }}</small></div><button class="text-button" :disabled="busy || !edge.id" @click="edit(edge)">编辑</button><button class="text-button danger" :disabled="busy || !edge.id" @click="remove(edge)">删除</button></article></section></BaseModal></template>
