<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { Bot, Activity, Bell, FileCog, Gauge, Workflow, ExternalLink } from '@lucide/vue';
import { useRoute, useRouter } from 'vue-router';
import DetailPanel from '@/components/DetailPanel.vue';
import InlineError from '@/components/InlineError.vue';
import LoadingState from '@/components/LoadingState.vue';
import EmptyState from '@/components/EmptyState.vue';
import ServiceRuntimeEvidence from './ServiceRuntimeEvidence.vue';
import type { TopologyV3Snapshot } from '@/api/observabilityV3';
import ServiceHealthBadge from './ServiceHealthBadge.vue';
import { observabilityApi, type ServiceDetail, type ServiceNode, type ConfigSummary, type TrafficSummary } from '@/api/observability';
import { useAuthStore } from '@/stores/auth';
import { useAiAssistantStore } from '@/stores/ai-assistant';
import { ciType, environmentNames } from '@/components/cmdb/topology';
import { effectiveHealth, observationLabels, healthScopeLabels, metric, observationTime, relationLabels, safeMetricUrl, serviceContext } from '@/utils/observability';
import { displayEndpoint } from '@/utils/service-endpoint';
const props = defineProps<{ node: ServiceNode; environment: string; timeRange: string; snapshot?: TopologyV3Snapshot; initialTab?: string; targetCiCode?: string }>();
const emit = defineEmits<{ close: [] }>();
const auth = useAuthStore(); const ai = useAiAssistantStore(); const route = useRoute(); const router = useRouter();
const detail = ref<ServiceDetail>(); const configSummary = ref<ConfigSummary>(); const trafficSummary = ref<TrafficSummary>(); const loading = ref(false); const error = ref(''); const tab = ref(props.initialTab || 'overview');
let epoch = 0; let timer: ReturnType<typeof setInterval> | undefined; let disposed = false;
const current = computed(() => detail.value?.node || props.node);
const context = computed(() => serviceContext(props.node.ciCode, props.environment, props.timeRange));
const tabs = computed(() => [{ key: 'overview', label: '概况' }, { key: 'diagnostics', label: '接入诊断' }, { key: 'metrics', label: '指标' }, { key: 'traffic', label: '流量' }, { key: 'config', label: '配置' }, { key: 'alerts', label: '告警' }, { key: 'relations', label: '关系' }, { key: 'runtime', label: '调用与实例' }].filter(tab => (!props.snapshot && !props.node.virtual) || ['overview', 'metrics', 'relations', 'diagnostics'].includes(tab.key)));
const cards = computed(() => { const m = detail.value?.node.metrics; return [{ label: '请求速率', value: metric(m?.rps, ' /s') }, { label: '错误率', value: metric(m?.errorRate == null ? null : m.errorRate, '%', 2) }, { label: 'P95 延迟', value: metric(m?.p95Ms, ' ms') }, { label: '健康实例', value: m?.totalInstances == null ? '—' : `${m.healthyInstances ?? '—'} / ${m.totalInstances}` }]; });
const metricLink = computed(() => safeMetricUrl(detail.value?.metricsUrl));
async function load() {
  if (props.snapshot || props.node.virtual) { epoch++; loading.value = false; error.value = ''; const code = props.node.ciCode; detail.value = { node: props.node, alerts: [], alertsAvailable: false, recentChanges: [], recentRuns: [], relations: (props.snapshot?.edges || []).filter(edge => edge.sourceCiCode === code || edge.targetCiCode === code), checkedAt: props.snapshot?.checkedAt, dataSources: props.snapshot?.dataSources }; configSummary.value = undefined; trafficSummary.value = undefined; return; }
  const own = ++epoch; const code = props.node.ciCode; const token = auth.token; loading.value = true; error.value = '';
  const result = await Promise.allSettled([observabilityApi.service(code, { environment: props.environment, timeRange: props.timeRange }), observabilityApi.configSummary(code), observabilityApi.trafficSummary(code)]);
  if (disposed || own !== epoch || token !== auth.token) return;
  if (result[0].status === 'fulfilled' && result[0].value.node.ciCode === code) detail.value = result[0].value;
  else { detail.value = undefined; error.value = result[0].status === 'rejected' && result[0].reason instanceof Error ? result[0].reason.message : '服务详情与当前选择不匹配'; }
  configSummary.value = result[1].status === 'fulfilled' ? result[1].value : { status: 'UNAVAILABLE', message: '配置摘要暂不可用，请在配置中心重试' };
  trafficSummary.value = result[2].status === 'fulfilled' ? result[2].value : { status: 'UNAVAILABLE', message: '流量摘要暂不可用，请在流量治理重试' };
  loading.value = false;
}
function go(path: string, extra: Record<string, string> = {}) { emit('close'); void router.push({ path, query: { ...context.value, ...extra, from: route.path } }); }
function analyze() { emit('close'); ai.show({ service: props.node.ciCode, environment: current.value.identity?.environment || current.value.environment, timeRange: props.timeRange }); if (!ai.question) ai.question = '请分析当前服务的异常现象、证据和可能原因，并说明还需要核对哪些信息。'; }
function title(row: Record<string, unknown>) { return String(row.title || row.summary || row.alertName || row.name || row.id || '关联记录'); }
function openRun(run: Record<string, unknown>) { if (run.source === 'DEMO_INCIDENT') go('/automation', { tab: 'experience', target: props.node.ciCode, incidentId: String(run.id) }); else go('/automation', { run: String(run.id), tab: 'runs' }); }
watch(() => [props.node.ciCode, props.environment, props.timeRange, props.snapshot, props.initialTab, auth.token], () => { epoch++; detail.value = undefined; configSummary.value = undefined; trafficSummary.value = undefined; tab.value = props.initialTab || 'overview'; if (auth.token) void load(); });
onMounted(() => { void load(); timer = setInterval(() => { if (!document.hidden && !props.snapshot && !loading.value) void load(); }, 15_000); });
onBeforeUnmount(() => { disposed = true; epoch++; clearInterval(timer); });
</script>
<template>
  <DetailPanel :title="node.ciName" :subtitle="node.ciCode" width="wide" @close="emit('close')">
    <p v-if="snapshot" class="obs-source-note">历史快照 {{ observationTime(snapshot.checkedAt) }} · 以下内容不读取当前运行状态。</p>
    <div class="obs-drawer-identity"><span class="obs-type-icon"><component :is="ciType(node.ciType).icon" :size="24" /></span><div><strong>{{ ciType(node.ciType).label }} · {{ environmentNames[node.environment] || node.environment }}</strong><p>{{ current.observation?.message || current.statusReason || '等待现场状态' }}</p></div><ServiceHealthBadge :health="error ? 'UNKNOWN' : effectiveHealth(current)" /></div>
    <nav class="obs-detail-tabs" aria-label="服务详情"><button v-for="item in tabs" :key="item.key" :class="{ active: tab === item.key }" @click="tab = item.key">{{ item.label }}<span v-if="item.key === 'alerts'">{{ detail?.alertsAvailable === false ? '—' : detail?.node.activeAlertCount ?? '—' }}</span></button></nav>
    <InlineError v-if="error" :message="error" /><LoadingState v-if="loading && !detail" text="读取服务现场证据…" />
    <div v-if="tab === 'overview'" class="obs-drawer-section"><div class="obs-metric-grid"><article v-for="card in cards" :key="card.label"><span>{{ card.label }}</span><strong>{{ card.value }}</strong></article></div><dl class="oa-definition-list"><div><dt>负责人</dt><dd>{{ current.ownerName || '未登记' }}</dd></div><div><dt>所属系统</dt><dd>{{ current.systemName || '未登记' }}</dd></div><div><dt>地址</dt><dd><code>{{ displayEndpoint(current.endpoint) }}</code></dd></div><div><dt>采样时间</dt><dd>{{ observationTime(current.observedAt) }}</dd></div><div><dt>服务说明</dt><dd>{{ current.description || '暂无说明' }}</dd></div></dl><div v-if="!snapshot" class="obs-context-cards"><button @click="tab = 'alerts'"><Bell :size="18" /><span>当前活动告警<strong>{{ detail && detail.alertsAvailable !== false ? detail.node.activeAlertCount ?? '—' : '—' }}</strong></span></button><button @click="tab = 'config'"><FileCog :size="18" /><span>近期配置变更<strong>{{ detail ? detail.recentChanges.length : '—' }}</strong></span></button></div><section v-if="!snapshot" class="obs-related"><h3>关联演练与恢复</h3><p v-if="!detail?.recentRuns.length" class="obs-muted">当前权限范围内暂无关联演练或运行。</p><button v-for="run in detail?.recentRuns" :key="String(run.id)" class="obs-record" @click="openRun(run)"><strong>{{ title(run) }}</strong><span>{{ run.status }}</span></button></section></div>
    <div v-else-if="tab === 'diagnostics'" class="obs-drawer-section"><div class="obs-source-note"><strong>{{ current.observation ? observationLabels[current.observation.status] : '接入状态尚未获取' }}</strong><span>{{ current.observation?.message || current.statusReason }}</span></div><dl class="oa-definition-list"><div><dt>健康证据范围</dt><dd>{{ healthScopeLabels[current.healthScope || ''] || current.healthScope || '尚未声明，不等同于业务全部正常' }}</dd></div><div><dt>服务身份</dt><dd>{{ current.identity?.ciCode || current.ciCode }} · {{ current.identity?.environment || current.environment }}</dd></div><div><dt>命名空间 / 集群</dt><dd>{{ current.identity?.namespace || '未声明' }} / {{ current.identity?.cluster || '未声明' }}</dd></div><div><dt>采集绑定</dt><dd>{{ current.bindings?.prometheusJob || '尚未配置 Prometheus 绑定' }}</dd></div><div><dt>最近有效样本</dt><dd>{{ observationTime(current.observation?.sampledAt || current.observedAt) }}</dd></div><div><dt>最近成功抓取</dt><dd>{{ observationTime(current.observation?.lastSuccessfulScrapeAt) }}</dd></div><div><dt>本次读取时间</dt><dd>{{ observationTime(current.observation?.fetchedAt) }} · 读取时间不会替代样本时间</dd></div></dl><article v-for="(check, index) in current.observation?.checks" :key="index" class="obs-relation-record"><strong>{{ check.name || check.step || '检查步骤' }} · {{ check.status }}</strong><span>{{ check.message || check.reasonCode || '未返回具体说明' }}</span></article><p v-if="!current.observation?.checks?.length" class="obs-muted">尚未取得分步骤诊断证据，请刷新或核对采集绑定。</p><template v-if="!snapshot"><button class="button secondary" :disabled="loading" @click="load">重新读取接入证据</button><button class="button secondary" @click="go('/observability/metrics')">查看采集目标</button></template></div>
    <div v-else-if="tab === 'metrics'" class="obs-drawer-section"><div class="obs-metric-grid"><article v-for="card in cards" :key="card.label"><span>{{ card.label }}</span><strong>{{ card.value }}</strong></article><article><span>CPU</span><strong>{{ metric(current.metrics?.cpuUsage == null ? null : current.metrics.cpuUsage, '%') }}</strong></article><article><span>内存使用</span><strong>{{ metric(current.metrics?.memoryUsage == null ? null : current.metrics.memoryUsage, '%') }}</strong></article></div><p class="obs-muted">按所选时间窗口聚合。缺少监控绑定或有效样本时显示“—”，不推断为零。</p><a v-if="metricLink && !snapshot" class="button secondary" :href="metricLink" target="_blank" rel="noopener noreferrer">查看指标趋势<ExternalLink :size="15" /></a><button v-else-if="!snapshot" class="button secondary" @click="go('/observability/metrics')">查看指标趋势与采集</button></div>
    <div v-else-if="tab === 'traffic'" class="obs-drawer-section"><div class="obs-metric-grid"><article><span>Sentinel 通过 QPS</span><strong>{{ metric(trafficSummary?.passQps, ' /s') }}</strong></article><article><span>Sentinel 阻断</span><strong>{{ metric(trafficSummary?.blockQps, ' /s') }}</strong></article><article><span>已观测资源</span><strong>{{ trafficSummary?.resourceCount ?? '—' }}</strong></article><article><span>生效规则</span><strong>{{ trafficSummary?.ruleCount ?? '—' }}</strong></article></div><p class="obs-muted">{{ trafficSummary?.message }} 规则由流量治理统一管理。当前绑定：{{ current.bindings?.sentinelApp || '未登记 Sentinel App' }}</p><button class="button primary" @click="go('/observability/traffic')"><Gauge :size="16" />查看流量与规则</button></div>
    <div v-else-if="tab === 'config'" class="obs-drawer-section"><div class="obs-metric-grid"><article><span>配置项</span><strong>{{ configSummary?.configurationCount ?? '—' }}</strong></article><article><span>受控可编辑项</span><strong>{{ configSummary?.editableCount ?? '—' }}</strong></article></div><div class="obs-source-note"><span v-for="source in configSummary?.sources" :key="source.source">{{ source.source }} · {{ source.count }} 项</span><span>{{ configSummary?.message }}</span></div><p class="obs-muted">配置绑定：{{ current.bindings?.nacosDataId || '未登记 Nacos Data ID' }}</p><div v-for="change in detail?.recentChanges" :key="String(change.id || change.revision)" class="obs-record"><strong>{{ title(change) }}</strong><small>{{ observationTime(String(change.occurredAt || change.createdAt || change.changedAt || '')) }} · {{ change.actor }} · {{ change.revision }}</small></div><EmptyState v-if="!detail?.recentChanges.length" title="暂无可见变更记录" description="在配置中心核对来源、版本和发布记录。" /><button class="button primary" @click="go('/observability/config')"><FileCog :size="16" />进入配置中心</button></div>
    <div v-else-if="tab === 'alerts'" class="obs-drawer-section"><p class="obs-muted">仅显示 {{ node.ciName }} 的当前上下文摘要，最多展示 5 条。</p><InlineError v-if="detail?.alertsAvailable === false" message="告警数据源暂不可用，无法确认当前活动告警。" /><article v-for="alert in detail?.alerts" :key="String(alert.id || alert.fingerprint)" class="obs-alert-record"><strong>{{ title(alert) }}</strong><p>{{ alert.summary || alert.description || alert.message || '' }}</p><div><span>{{ alert.severity || alert.status }}</span><button v-if="alert.ticketId" class="text-button" @click="go(`/tickets/${alert.ticketId}`)">查看关联事件</button></div></article><EmptyState v-if="detail && detail.alertsAvailable !== false && !detail.alerts.length" title="没有匹配的活动告警" description="告警来源的可用性请结合下方数据源状态确认。" /><button class="button secondary" @click="go('/itsm/alerts')"><Bell :size="16" />查看全部告警（保留服务筛选）</button></div>
    <ServiceRuntimeEvidence v-else-if="tab === 'runtime' && !snapshot && !node.virtual" :ci-code="node.ciCode" :environment="environment" :time-range="timeRange" :target-ci-code="targetCiCode" />
    <div v-else class="obs-drawer-section"><article v-for="(edge, index) in detail?.relations" :key="edge.id || index" class="obs-relation-record"><strong>{{ edge.sourceCiCode }} → {{ edge.targetCiCode }}</strong><small>{{ relationLabels[edge.relationType] || edge.relationType }} · {{ edge.relationSource || 'CMDB' }}</small></article><EmptyState v-if="detail && !detail.relations.length" title="尚未登记依赖关系" description="管理员可以在编辑拓扑中维护有向依赖。" /></div>
    <div v-if="detail?.dataSources?.some(source => !source.healthy)" class="obs-source-note"><p v-for="source in detail.dataSources.filter(item => !item.healthy)" :key="source.name">{{ source.name }}：{{ source.message || '数据暂不可用' }}</p></div>
    <template v-if="!snapshot && !node.virtual" #footer><div class="obs-drawer-actions"><button class="button primary" @click="analyze"><Bot :size="16" />AI 分析当前服务</button><button class="button secondary" @click="go('/automation')"><Workflow :size="16" />进入自动化</button><button class="button secondary" @click="go('/observability/inspections')"><Activity :size="16" />持续巡检</button></div></template>
  </DetailPanel>
</template>
