<script setup lang="ts">
import { ref } from 'vue';
import BaseModal from '@/components/BaseModal.vue';
import InlineError from '@/components/InlineError.vue';
import { itsmApi } from '@/api/modules';
import { observabilityApi, type ServiceNode } from '@/api/observability';
import { ciTypes, environmentNames } from '@/components/cmdb/topology';
import { useAuthStore } from '@/stores/auth';
const props = defineProps<{ node?: ServiceNode }>();
const emit = defineEmits<{ close: []; saved: [] }>();
const auth = useAuthStore();
const form = ref({ ciCode: props.node?.ciCode || '', ciName: props.node?.ciName || '', ciType: props.node?.ciType || 'SERVICE', environment: props.node?.environment || 'PROD', ownerName: props.node?.ownerName || '', endpoint: props.node?.endpoint || '', description: props.node?.description || '', status: props.node?.status || 'ACTIVE', systemName: props.node?.systemName || '', tags: props.node?.tags?.join(', ') || '', bindings: { ...props.node?.bindings, prometheusJob: props.node?.bindings?.prometheusJob || '', sentinelApp: props.node?.bindings?.sentinelApp || '', nacosDataId: props.node?.bindings?.nacosDataId || '', alertLabel: props.node?.bindings?.alertLabel || '' } });
const busy = ref(false); const error = ref(''); const confirmDelete = ref(false);
async function save() { if (!auth.isAdmin || busy.value) return; busy.value = true; error.value = ''; try { const payload = { ...form.value, tags: form.value.tags.split(/[,，]/).map(tag => tag.trim()).filter(Boolean) }; if (props.node?.id) await itsmApi.updateCi(props.node.id, payload); else await itsmApi.createCi(payload); emit('saved'); } catch (cause) { error.value = cause instanceof Error ? cause.message : '保存失败'; } finally { busy.value = false; } }
async function remove() { if (!auth.isAdmin || !props.node?.id || !confirmDelete.value || busy.value) return; busy.value = true; error.value = ''; try { await observabilityApi.deleteCi(props.node.id); emit('saved'); } catch (cause) { error.value = cause instanceof Error ? cause.message : '删除失败'; } finally { busy.value = false; } }
</script>
<template><BaseModal :title="node ? '编辑服务节点' : '登记服务节点'" @close="emit('close')"><form class="form-grid obs-editor" @submit.prevent="save"><InlineError v-if="error" class="full" :message="error" /><label>CI 编码<input v-model.trim="form.ciCode" :readonly="!!node" required maxlength="64" pattern="[a-zA-Z0-9._-]+" /></label><label>名称<input v-model.trim="form.ciName" required maxlength="128" /></label><label>类型<select v-model="form.ciType"><option v-for="(type, key) in ciTypes" :key="key" :value="key">{{ type.label }}</option></select></label><label>环境<select v-model="form.environment"><option v-for="(name, key) in environmentNames" :key="key" :value="key">{{ name }}</option></select></label><label>负责人<input v-model.trim="form.ownerName" maxlength="64" /></label><label>所属系统<input v-model.trim="form.systemName" maxlength="128" /></label><label>状态<select v-model="form.status"><option value="ACTIVE">启用</option><option value="INACTIVE">停用维护</option></select></label><label>标签<input v-model.trim="form.tags" maxlength="500" placeholder="以逗号分隔" /></label><label class="full">访问地址<input v-model.trim="form.endpoint" maxlength="255" placeholder="仅登记地址，不包含账号、密码或令牌" /></label><label class="full">说明<textarea v-model.trim="form.description" rows="3" maxlength="500" /></label><div class="full obs-form-section">观测绑定<span>使用已存在的目标名称关联现场数据</span></div><label>Prometheus Job<input v-model.trim="form.bindings.prometheusJob" maxlength="128" /></label><label>Sentinel App<input v-model.trim="form.bindings.sentinelApp" maxlength="128" /></label><label>Nacos Data ID<input v-model.trim="form.bindings.nacosDataId" maxlength="128" /></label><label>Alertmanager 服务标签<input v-model.trim="form.bindings.alertLabel" maxlength="128" placeholder="如 ops-rag-service" /></label><div v-if="node?.id" class="full obs-delete"><label><input v-model="confirmDelete" type="checkbox" />确认删除台账节点及关联关系（不会停止实际服务）</label><button type="button" class="text-button danger" :disabled="!confirmDelete || busy" @click="remove">删除节点</button></div><div class="form-actions full"><button type="button" class="button secondary" :disabled="busy" @click="emit('close')">取消</button><button class="button primary" :disabled="busy || !auth.isAdmin">{{ busy ? '保存中…' : '保存节点' }}</button></div></form></BaseModal></template>
