ssl_certificate /etc/letsencrypt/live/opsagent.cloud/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/opsagent.cloud/privkey.pem;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_cache shared:OpsAgentTLS:10m;
ssl_session_timeout 1d;
ssl_session_tickets off;
