<script setup lang="ts">
import { ArrowRight, CalendarClock, ShieldAlert } from "@lucide/vue";
import { ref, watch } from "vue";
const props = defineProps<{ priority: number; slaRisk: number; alerts: number; onCallName: string; ready: boolean }>();
const active = ref('attention');
let initialized = false;
watch(() => props.ready, ready => { if (ready && !initialized) { active.value = props.priority || props.slaRisk || props.alerts ? 'attention' : 'oncall'; initialized = true; } }, { immediate: true });
function move(event: KeyboardEvent) { if (!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(event.key)) return; event.preventDefault(); active.value = event.key === 'Home' ? 'attention' : event.key === 'End' ? 'oncall' : active.value === 'attention' ? 'oncall' : 'attention'; const root = (event.currentTarget as HTMLElement); (root.querySelector(`[data-focus-tab="${active.value}"]`) as HTMLElement)?.focus(); }
</script>
<template><section class="dashboard-focus" aria-label="当前重点"><div class="focus-tabs" role="tablist" aria-label="选择关注内容" @keydown="move"><button id="focus-attention-tab" data-focus-tab="attention" role="tab" :aria-selected="active === 'attention'" :tabindex="active === 'attention' ? 0 : -1" aria-controls="dashboard-focus-content" @click="active = 'attention'"><ShieldAlert :size="17" />需要处理</button><button id="focus-oncall-tab" data-focus-tab="oncall" role="tab" :aria-selected="active === 'oncall'" :tabindex="active === 'oncall' ? 0 : -1" aria-controls="dashboard-focus-content" @click="active = 'oncall'"><CalendarClock :size="17" />值班与升级</button></div><div id="dashboard-focus-content" role="tabpanel" :aria-labelledby="`focus-${active}-tab`"><div :key="active" class="focus-content" data-motion="tab"><template v-if="!ready"><h2>正在汇总当前重点</h2><p>工单、SLA 与当前值班来自实时接口。</p></template><template v-else-if="active === 'attention'"><h2>{{ priority || slaRisk || alerts ? '先处理风险，让工作有序推进' : '当前未发现高优先级待办' }}</h2><p>{{ priority }} 个活跃 P1/P2 · {{ slaRisk }} 个 SLA 风险<span v-if="alerts"> · {{ alerts }} 条未恢复告警</span></p><RouterLink :to="slaRisk ? '/itsm/sla?view=risk' : '/tickets'">{{ slaRisk ? '查看 SLA 风险' : '查看活跃工单' }}<ArrowRight :size="15" /></RouterLink></template><template v-else><h2>{{ onCallName === '未排班' ? '为下一次告警明确责任人' : `当前值班：${onCallName}` }}</h2><p>查看主备值班与班次时间，确认升级时能找到对应负责人。</p><RouterLink to="/itsm/oncall">查看值班与升级<ArrowRight :size="15" /></RouterLink></template></div></div><div class="focus-symbol" aria-hidden="true"><ShieldAlert v-if="active === 'attention'" :size="32" /><CalendarClock v-else :size="32" /></div></section></template>
