import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const require = createRequire(new URL('../package.json', import.meta.url));
const ts = require('typescript');
const { createSSRApp } = require('vue');
const { renderToString } = require('vue/server-renderer');
function load(path, replace = source => source) {
  const source = replace(readFileSync(fileURLToPath(new URL('../src/' + path, import.meta.url)), 'utf8'));
  const js = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
  const module = { exports: {} };
  new Function('require', 'module', 'exports', js)(require, module, module.exports);
  return module.exports;
}
const { renderAnswer } = load('utils/answer-markdown.ts');
const sample = '# 完整回答\n\n**风险**与`redis-cli`\n\n| 步骤 | 说明 |\n| --- | --- |\n| 1 | 检查连接 |\n\n---\n\n```sh\nredis-cli ping\n```\n\n<script>alert(1)</script>\n\n[坏链接](javascript:alert(1))\n\n## 三、证据\n最后一段 [S1]';
const html = await renderToString(createSSRApp({render: () => renderAnswer(sample)}));
assert.ok(html.includes('<strong>风险</strong>'));
assert.ok(html.includes('<table>') && html.includes('检查连接'));
assert.ok(html.includes('<pre>') && html.includes('<hr>'));
assert.ok(html.includes('最后一段 [S1]'));
assert.ok(!html.includes('<script>') && !html.includes('href="javascript:'));
console.log('PASS markdown: headings, emphasis, code, tables, trailing content and HTML/link safety');
globalThis.window = { setTimeout, clearTimeout };
globalThis.localStorage = { getItem: () => null };
const { streamRagAnswer, ragCompletionLabel } = load('api/rag-stream.ts', source => source.replaceAll('import.meta.env.VITE_API_BASE_URL', "''"));
const encoder = new TextEncoder();
const events = 'event: token\r\ndata: {"delta":"三、证据"}\r\n\r\nevent: token\r\ndata: {"delta":"\\n结尾完整。"}\r\n\r\nevent: done\r\ndata: {"answer":"三、证据\\n结尾完整。","provider":"test","model":"test","references":[],"metadata":{"generationComplete":true}}\r\n\r\n';
const bytes = encoder.encode(events);
globalThis.fetch = async () => new Response(new ReadableStream({ start(controller) { for (let i = 0; i < bytes.length; i++) controller.enqueue(bytes.slice(i, i + 1)); controller.close(); } }), {headers:{"Content-Type":"text/event-stream"}});
let collected = '';
const result = await streamRagAnswer({question:'x'}, {onToken: token => { collected += token; }});
assert.equal(collected, '三、证据\n结尾完整。');
assert.equal(result.answer, collected);
assert.equal(ragCompletionLabel({...result, metadata:{generationComplete:false}}), '回答未完成');
globalThis.fetch = async () => new Response('event: token\ndata: {"delta":"残文"}\n\n', {headers:{'Content-Type':'text/event-stream'}});
await assert.rejects(streamRagAnswer({question:'x'}), /提前结束/);
console.log('PASS SSE: byte-split UTF-8, split CRLF, complete final answer, incomplete metadata and missing done detection');
globalThis.fetch = async () => new Response(JSON.stringify({code:40400,message:'会话不存在或不可访问'}), {headers:{'Content-Type':'application/json'}});
await assert.rejects(streamRagAnswer({question:'x'}), /会话不存在或不可访问/);
console.log('PASS SSE endpoint preserves JSON business errors');
