import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(new URL('../package.json', import.meta.url));
const ts = require('typescript'), vue = require('vue'), compiler = require('vue/compiler-sfc');
function source(path) { return readFileSync(new URL('../src/' + path, import.meta.url), 'utf8'); }
function evaluate(code, imports = {}) { const module = { exports: {} }; new Function('require', 'module', 'exports', ts.transpileModule(code, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText)(name => imports[name] ?? (name.endsWith('.vue') || name.endsWith('.css') ? {} : require(name)), module, module.exports); return module.exports; }
const configUtil = evaluate(source('utils/configuration-files.ts'));
const queue = evaluate(source('utils/event-queue.ts'));
const knowledge = evaluate(source('utils/knowledge-stage.ts'));
const fields = [{ key: 'pool', label: '连接池', category: '数据库', type: 'integer', min: 1, max: 30, value: 5, editable: true }, { key: 'password', label: '密码', category: '数据库', type: 'string', sensitive: true, hasValue: true, editable: true }, { key: 'fixed', type: 'string', value: 'same', editable: false }];
assert.deepEqual(configUtil.configurationChanges(fields, { pool: 5, password: '', fixed: 'changed' }, {}), []);
assert.deepEqual(configUtil.configurationChanges(fields, { pool: '8', password: 'new-test-value' }, { password: true }), [{ key: 'pool', value: 8 }, { key: 'password', value: 'new-test-value' }]);
assert.throws(() => configUtil.configurationChanges(fields, { pool: '' }, {}), /有效数值/);
assert.throws(() => configUtil.configurationChanges(fields, { pool: 2.5 }, {}), /整数/);
assert.throws(() => configUtil.configurationChanges(fields, { pool: 31 }, {}), /范围/);
assert.equal(queue.queueState({ status: 'CLOSED', currentStage: 'VERIFYING', eventClosed: false }), '待验证', 'work-order closure must not close its event');
assert.equal(queue.queueStageLabel({ currentStage: 'READY_TO_CLOSE' }), '等待关闭');
assert.equal(queue.queueSla({}, 0).label, 'SLA 尚未取得');
assert.equal(queue.queueSla({ sla: { applicable: false } }, 0).label, '无适用规则');
assert.equal(queue.queueSla({ sla: { applicable: true, paused: true } }, 0).label, '计时已暂停');
assert.equal(queue.queueSla({ sla: { applicable: true, resolutionStatus: 'COMPLETED', resolutionDeadline: '2020-01-01' } }).label, '已完成计时');
assert.equal(knowledge.knowledgeStage({ status: 'PARSED', review_status: 'DRAFT', index_status: 'SUCCESS', chunk_count: 3 }).label, '待提交审核', 'an index alone cannot grant publication');
assert.equal(knowledge.knowledgeStage({ status: 'PARSED', review_status: 'PUBLISHED', index_status: 'PENDING', chunk_count: 3 }).label, '已发布待索引');
assert.equal(knowledge.knowledgeStage({ status: 'PARSED', review_status: 'PUBLISHED', index_status: 'SUCCESS', chunk_count: 3 }).label, '可检索');
assert.equal(knowledge.knowledgeStage({ status: 'PARSED', review_status: 'PUBLISHED', index_status: 'SUCCESS', chunk_count: 0 }).label, '内容待补齐');
console.log('PASS stage two: lifecycle-based queue state, missing versus absent SLA, publish/index/content distinction, typed bounds and explicit-only secret replacement');

const auth = vue.reactive({ token: 'test-a', isAdmin: true, isOps: false, isDemo: false, user: { userId: 1 } });
const calls = []; const api = { detail: async id => ({ id, serviceId: id, label: id, version: 'version-a', fields, editable: true, rawEditable: false, redactedContent: 'pool: 5', affectedServices: [id] }), create: async (id, body) => { calls.push(['create', id, body]); return { id: 'draft-a', digest: 'digest-a', status: 'DRAFT', action: body.action, baseVersion: body.baseVersion, diff: body.changes, targetVersion: 'version-b', affectedServices: [id] }; }, submit: async (id, digest, requestId) => { calls.push(['submit', id, digest, requestId]); return { ...state.draft.value, status: 'PENDING_APPROVAL' }; }, approve: async (id, digest, decision) => { calls.push(['approve', id, digest, decision]); return { ...state.draft.value, status: decision === 'APPROVE' ? 'APPROVED' : 'REJECTED' }; } };
const { descriptor } = compiler.parse(source('components/configuration/ConfigurationFiles.vue'));
const script = compiler.compileScript(descriptor, { id: 'file-management-test' });
const component = evaluate(script.content, { vue: { ...vue, onMounted() {}, onBeforeUnmount() {} }, 'vue-router': { onBeforeRouteLeave() {} }, '@lucide/vue': {}, '@/stores/auth': { useAuthStore: () => auth }, '@/api/configuration-files': { configurationFilesApi: api }, '@/utils/configuration-files': configUtil }).default;
const scope = vue.effectScope();
const state = scope.run(() => component.setup({}, { expose() {} }));
await state.select('service-a', true);
state.values.pool = 8;
await state.createDraft('PUBLISH_ONLY');
assert.equal(calls.length, 1, 'creating the review never submits, approves or executes');
assert.equal(calls[0][2].action, 'PUBLISH_ONLY'); assert.deepEqual(calls[0][2].changes, [{ key: 'pool', value: 8 }]);
await state.submit(); assert.equal(calls.length, 2); assert.equal(state.draft.value.status, 'PENDING_APPROVAL');
await state.approve('APPROVE'); assert.equal(calls.length, 3); assert.equal(state.draft.value.status, 'APPROVED');
assert(calls.every(call => call[0] !== 'execute'), 'approval is not execution');
api.create = async () => { throw new Error('VERSION_CONFLICT'); };
state.values.pool = 10; await state.createDraft('PUBLISH_RESTART'); assert.match(state.error.value, /VERSION_CONFLICT/); assert.equal(state.values.pool, 10, 'a conflicting version keeps the user edit');
state.task.value = { id: 'task-a', status: 'LOADED_PENDING_VERIFICATION', awaitingVerification: true, updatedAt: '2026-09-07T10:00:00' };
assert.equal(state.taskRunning.value, false, 'finished verification waits for evidence without polling forever');
assert.equal(state.canVerify.value, true);
api.verify = async (id, requestId) => { calls.push(['verify', id, requestId]); return { ...state.task.value, awaitingVerification: false }; };
await state.verifyTask(); assert.equal(calls.at(-1)[0], 'verify'); assert.equal(state.taskRunning.value, true);
state.task.value = { ...state.task.value, status: 'PUBLISHED_PENDING_APPLY', awaitingVerification: false }; assert.equal(state.canVerify.value, false, 'publish-only needs a new approved apply, not verification');
state.task.value = { ...state.task.value, status: 'ROLLED_BACK' }; assert.equal(state.canVerify.value, false);
auth.isAdmin = false; const count = calls.length; await state.createDraft('PUBLISH_ONLY'); assert.equal(calls.length, count, 'role downgrade blocks creation');
assert.equal(state.canRead.value, false, 'ordinary users cannot fetch controlled configuration contents');
scope.stop();
console.log('PASS real configuration file component: read/edit/review steps remain distinct, exact approved intent, conflict retains edits, administrator creation gate');
