CREATE TABLE IF NOT EXISTS agent_runtime_guard (id INT PRIMARY KEY);
INSERT IGNORE INTO agent_runtime_guard(id) VALUES(1);
CREATE TABLE IF NOT EXISTS agent_definition (
 id VARCHAR(80) PRIMARY KEY, name VARCHAR(120) NOT NULL, draft_json LONGTEXT NOT NULL,
 draft_revision INT NOT NULL DEFAULT 1, published_version INT NOT NULL DEFAULT 0,
 updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE TABLE IF NOT EXISTS agent_version (
 definition_id VARCHAR(80) NOT NULL, version INT NOT NULL, snapshot_json LONGTEXT NOT NULL,
 snapshot_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY(definition_id,version)
);
CREATE TABLE IF NOT EXISTS agent_run (
 id VARCHAR(64) PRIMARY KEY, trigger_key VARCHAR(180) NOT NULL UNIQUE,
 definition_id VARCHAR(80) NOT NULL, version INT NOT NULL, owner_id BIGINT NOT NULL,
 ticket_id BIGINT NOT NULL, incident_id VARCHAR(36) NOT NULL,
 status VARCHAR(32) NOT NULL, node_id VARCHAR(80) NOT NULL, snapshot_json LONGTEXT NOT NULL,
 state_json LONGTEXT NOT NULL, fence BIGINT NOT NULL DEFAULT 0,
 lease_until TIMESTAMP(3) NULL, next_attempt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
 pause_requested BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 INDEX idx_run_ready(status,next_attempt,lease_until), INDEX idx_run_owner(owner_id,created_at)
);
CREATE TABLE IF NOT EXISTS agent_event (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, run_id VARCHAR(64) NOT NULL, event_type VARCHAR(64) NOT NULL,
 node_id VARCHAR(80) NOT NULL, payload_json LONGTEXT NOT NULL,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX idx_event_run(run_id,id)
);
CREATE TABLE IF NOT EXISTS agent_approval (
 id VARCHAR(64) PRIMARY KEY, run_id VARCHAR(64) NOT NULL, call_id VARCHAR(160) NOT NULL,
 args_hash VARCHAR(64) NOT NULL, payload_json LONGTEXT NOT NULL, status VARCHAR(24) NOT NULL,
 revision INT NOT NULL DEFAULT 1, decided_by BIGINT NULL, reason VARCHAR(500) NULL,
 expires_at TIMESTAMP(3) NOT NULL, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_approval_call(run_id,call_id)
);
CREATE TABLE IF NOT EXISTS agent_outbox (
 id VARCHAR(64) PRIMARY KEY, run_id VARCHAR(64) NOT NULL, sent BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE TABLE IF NOT EXISTS agent_trigger (
 id VARCHAR(180) PRIMARY KEY, payload_json LONGTEXT NOT NULL, status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
 next_attempt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), last_error VARCHAR(350) NULL,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
